# Generated by Django 4.2.7 on 2025-03-14 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_type', models.CharField(choices=[('affected_entity', 'The affected entity'), ('reporting_other', 'Reporting incident affecting other entity')], max_length=20)),
                ('reporter_identity', models.CharField(choices=[('individual', 'Individual'), ('organization', 'Organization')], max_length=20)),
                ('name_role', models.CharField(max_length=255, verbose_name='Name & Role/Title')),
                ('organization_name', models.CharField(blank=True, max_length=255, verbose_name='Organization name (if any)')),
                ('contact_no', models.CharField(max_length=50, verbose_name='Contact No.')),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('affected_entity', models.CharField(blank=True, max_length=255, verbose_name='Affected entity (if not same as reporting entity)')),
                ('incident_types', models.JSONField(default=dict)),
                ('other_incident_details', models.TextField(blank=True)),
                ('is_critical', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5, verbose_name="Is the affected system/network critical to the organization's mission?")),
                ('critical_details', models.TextField(blank=True, verbose_name='Brief details')),
                ('system_info', models.TextField(verbose_name='Basic Information of Affected System')),
                ('domain_url', models.CharField(blank=True, max_length=255, verbose_name='Domain/URL')),
                ('ip_address', models.CharField(blank=True, max_length=50, verbose_name='IP Address')),
                ('operating_system', models.CharField(blank=True, max_length=100, verbose_name='Operating System')),
                ('make_model', models.CharField(blank=True, max_length=255, verbose_name='Make/Model/Cloud details')),
                ('app_details', models.TextField(blank=True, verbose_name='Affected Application details (if any)')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Location of affected system (including City, Region & Country)')),
                ('isp_info', models.CharField(blank=True, max_length=255, verbose_name='Network and name of ISP')),
                ('incident_description', models.TextField(verbose_name='Brief description of Incident')),
                ('occurrence_date', models.DateTimeField(blank=True, null=True, verbose_name='Occurrence date & time')),
                ('detection_date', models.DateTimeField(blank=True, null=True, verbose_name='Detection date & time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
